import type {
  AppMeta,
  ApprovalItem,
  Country,
  CountryPipelineSnapshot,
  DashboardMetric,
  Department,
  DocumentAutomationCard,
  DocumentTemplate,
  ExecutiveBriefing,
  LanguageCoverage,
  NotificationItem,
  SentimentInsight,
  UserDirectoryEntry,
  Workflow,
  WorkflowPlaybook,
} from "@bracco/types";

export const appMeta: AppMeta = {
  name: "Bracco Process Hub",
  tagline: "Enterprise workflow orchestration for regional operating teams",
  description:
    "A placeholder internal platform that aligns commercial, procurement, finance, legal, and executive approvals across markets.",
};

export const dashboardMetrics: DashboardMetric[] = [
  { label: "Active workflows", value: "38", delta: "+12% vs. last cycle", tone: "up" },
  { label: "Median cycle time", value: "6.8 days", delta: "-1.4 days", tone: "up" },
  { label: "AI sentiment alerts", value: "7", delta: "3 need legal review", tone: "neutral" },
  { label: "Template automation", value: "84%", delta: "+9 templates onboarded", tone: "up" },
];

export const executiveBriefings: ExecutiveBriefing[] = [
  {
    id: "brief-1",
    title: "Regional launch pacing aligned",
    message:
      "Commercial and finance are tracking inside threshold for the next two market submissions.",
    owner: "Executive Programme Office",
    eta: "Reviewed 2 hours ago",
  },
  {
    id: "brief-2",
    title: "Contracting bottleneck isolated",
    message:
      "Procurement escalations are concentrated in two vendor packages and already routed to legal.",
    owner: "Global Procurement PMO",
    eta: "Next checkpoint in 6 hours",
  },
  {
    id: "brief-3",
    title: "Language coverage ready",
    message:
      "Spanish, Italian, Portuguese, and Arabic review packs are synchronized for the same approval window.",
    owner: "Market Operations",
    eta: "Translation review tonight",
  },
];

export const departmentCatalog: Department[] = [
  {
    id: "dept-commercial",
    code: "commercial",
    name: "Commercial",
    mandate: "Owns market need, forecast assumptions, and launch timing.",
    leader: "Regional Commercial Excellence",
    escalationWindowHours: 24,
  },
  {
    id: "dept-procurement",
    code: "procurement",
    name: "Procurement",
    mandate: "Qualifies vendors, pricing terms, and sourcing readiness.",
    leader: "Global Procurement PMO",
    escalationWindowHours: 36,
  },
  {
    id: "dept-finance",
    code: "finance",
    name: "Finance",
    mandate: "Validates spend controls, budget allocation, and payment exposure.",
    leader: "Regional Finance Control",
    escalationWindowHours: 24,
  },
  {
    id: "dept-legal",
    code: "legal",
    name: "Legal",
    mandate: "Handles contracts, data governance, and market-specific obligations.",
    leader: "Legal Operations",
    escalationWindowHours: 48,
  },
  {
    id: "dept-executive-management",
    code: "executive_management",
    name: "Executive Management",
    mandate: "Approves strategic exceptions, capital thresholds, and high-visibility decisions.",
    leader: "Executive Steering Committee",
    escalationWindowHours: 72,
  },
];

export const countryCoverage: Country[] = [
  {
    id: "country-it",
    code: "IT",
    name: "Italy",
    region: "Southern Europe",
    defaultLanguage: "Italian",
    languages: ["Italian", "English"],
    complianceFocus: "Healthcare event sponsorship review",
    coordinationModel: "Milan hub with central legal sign-off",
  },
  {
    id: "country-es",
    code: "ES",
    name: "Spain",
    region: "Iberia",
    defaultLanguage: "Spanish",
    languages: ["Spanish", "English"],
    complianceFocus: "Distributor pricing controls",
    coordinationModel: "Madrid market cell with shared finance queue",
  },
  {
    id: "country-mx",
    code: "MX",
    name: "Mexico",
    region: "Latin America",
    defaultLanguage: "Spanish",
    languages: ["Spanish", "English"],
    complianceFocus: "Vendor onboarding and tax packet checks",
    coordinationModel: "Mexico City cluster with LATAM procurement oversight",
  },
  {
    id: "country-br",
    code: "BR",
    name: "Brazil",
    region: "Latin America",
    defaultLanguage: "Portuguese",
    languages: ["Portuguese", "English"],
    complianceFocus: "Medical education event contracting",
    coordinationModel: "Sao Paulo operations pod with regional executive review",
  },
  {
    id: "country-ae",
    code: "AE",
    name: "United Arab Emirates",
    region: "Middle East",
    defaultLanguage: "English",
    languages: ["English", "Arabic"],
    complianceFocus: "Arabic document traceability and executive exceptions",
    coordinationModel: "Dubai affiliate with shared legal documentation desk",
  },
];

export const teamDirectory: UserDirectoryEntry[] = [
  {
    id: "user-rossi",
    name: "Elena Rossi",
    title: "Commercial Operations Lead",
    department: "commercial",
    countryCode: "IT",
    email: "elena.rossi@braccoprocesshub.example",
    languages: ["Italian", "English"],
  },
  {
    id: "user-ortega",
    name: "Sofia Ortega",
    title: "Procurement Programme Manager",
    department: "procurement",
    countryCode: "MX",
    email: "sofia.ortega@braccoprocesshub.example",
    languages: ["Spanish", "English"],
  },
  {
    id: "user-keller",
    name: "Martin Keller",
    title: "Regional Finance Controller",
    department: "finance",
    countryCode: "ES",
    email: "martin.keller@braccoprocesshub.example",
    languages: ["Spanish", "English", "German"],
  },
  {
    id: "user-almeida",
    name: "Paula Almeida",
    title: "Legal Operations Counsel",
    department: "legal",
    countryCode: "BR",
    email: "paula.almeida@braccoprocesshub.example",
    languages: ["Portuguese", "English"],
  },
  {
    id: "user-haddad",
    name: "Nadia Haddad",
    title: "Executive Portfolio Director",
    department: "executive_management",
    countryCode: "AE",
    email: "nadia.haddad@braccoprocesshub.example",
    languages: ["Arabic", "English", "French"],
  },
];

export const featuredWorkflows: Workflow[] = [
  {
    id: "wf-001",
    title: "Imaging vendor onboarding",
    summary:
      "Approve a new vendor pack for imaging site support with synchronized commercial, legal, and finance checks.",
    requestedBy: "Global Procurement PMO",
    countryCode: "IT",
    language: "Italian",
    priority: "high",
    status: "in_review",
    dueDate: "2026-03-18",
    steps: [
      {
        id: "wf-001-step-1",
        order: 1,
        department: "commercial",
        title: "Business need confirmation",
        owner: "Elena Rossi",
        slaHours: 24,
        status: "approved",
      },
      {
        id: "wf-001-step-2",
        order: 2,
        department: "procurement",
        title: "Vendor due diligence",
        owner: "Sofia Ortega",
        slaHours: 36,
        status: "in_review",
      },
      {
        id: "wf-001-step-3",
        order: 3,
        department: "finance",
        title: "Budget line validation",
        owner: "Martin Keller",
        slaHours: 24,
        status: "pending",
      },
      {
        id: "wf-001-step-4",
        order: 4,
        department: "legal",
        title: "Contract clause review",
        owner: "Paula Almeida",
        slaHours: 48,
        status: "pending",
      },
      {
        id: "wf-001-step-5",
        order: 5,
        department: "executive_management",
        title: "Executive threshold sign-off",
        owner: "Nadia Haddad",
        slaHours: 72,
        status: "pending",
      },
    ],
  },
  {
    id: "wf-002",
    title: "Regional event contracting",
    summary:
      "Coordinate a multi-market education event package with Spanish and Portuguese documentation variants.",
    requestedBy: "Market Operations Iberia-LATAM",
    countryCode: "BR",
    language: "Portuguese",
    priority: "critical",
    status: "awaiting_approval",
    dueDate: "2026-03-15",
    steps: [
      {
        id: "wf-002-step-1",
        order: 1,
        department: "commercial",
        title: "Programme scope lock",
        owner: "Elena Rossi",
        slaHours: 24,
        status: "approved",
      },
      {
        id: "wf-002-step-2",
        order: 2,
        department: "procurement",
        title: "Venue and vendor terms",
        owner: "Sofia Ortega",
        slaHours: 36,
        status: "approved",
      },
      {
        id: "wf-002-step-3",
        order: 3,
        department: "finance",
        title: "Spend release approval",
        owner: "Martin Keller",
        slaHours: 24,
        status: "in_review",
      },
      {
        id: "wf-002-step-4",
        order: 4,
        department: "legal",
        title: "Speaker contract package",
        owner: "Paula Almeida",
        slaHours: 48,
        status: "at_risk",
      },
      {
        id: "wf-002-step-5",
        order: 5,
        department: "executive_management",
        title: "Executive final release",
        owner: "Nadia Haddad",
        slaHours: 72,
        status: "pending",
      },
    ],
  },
  {
    id: "wf-003",
    title: "Distributor rebate refresh",
    summary:
      "Refresh a commercial rebate framework with new controls for the Mexico affiliate and shared finance review.",
    requestedBy: "LATAM Commercial Excellence",
    countryCode: "MX",
    language: "Spanish",
    priority: "standard",
    status: "changes_requested",
    dueDate: "2026-03-22",
    steps: [
      {
        id: "wf-003-step-1",
        order: 1,
        department: "commercial",
        title: "Rebate scenario update",
        owner: "Elena Rossi",
        slaHours: 24,
        status: "approved",
      },
      {
        id: "wf-003-step-2",
        order: 2,
        department: "procurement",
        title: "Third-party support check",
        owner: "Sofia Ortega",
        slaHours: 36,
        status: "approved",
      },
      {
        id: "wf-003-step-3",
        order: 3,
        department: "finance",
        title: "Accrual alignment",
        owner: "Martin Keller",
        slaHours: 24,
        status: "at_risk",
      },
      {
        id: "wf-003-step-4",
        order: 4,
        department: "legal",
        title: "Commercial terms amendments",
        owner: "Paula Almeida",
        slaHours: 48,
        status: "pending",
      },
      {
        id: "wf-003-step-5",
        order: 5,
        department: "executive_management",
        title: "Strategic exception decision",
        owner: "Nadia Haddad",
        slaHours: 72,
        status: "pending",
      },
    ],
  },
];

export const workflowPlaybooks: WorkflowPlaybook[] = [
  {
    id: "playbook-1",
    name: "Vendor onboarding",
    primaryDepartment: "procurement",
    description: "Standardized onboarding path for suppliers, service partners, and outsourced operations.",
    markets: ["IT", "MX", "AE"],
    averageCycleDays: 7,
  },
  {
    id: "playbook-2",
    name: "Event contracting",
    primaryDepartment: "legal",
    description: "Cross-border contracting for congresses, education events, and speaker engagements.",
    markets: ["ES", "BR", "IT"],
    averageCycleDays: 9,
  },
  {
    id: "playbook-3",
    name: "Commercial pricing update",
    primaryDepartment: "finance",
    description: "Budget and legal validation path for pricing, rebate, and market access exceptions.",
    markets: ["MX", "ES", "AE"],
    averageCycleDays: 6,
  },
];

export const approvalQueue: ApprovalItem[] = [
  {
    id: "approval-1",
    workflowId: "wf-001",
    workflowTitle: "Imaging vendor onboarding",
    department: "procurement",
    approver: "Sofia Ortega",
    status: "pending",
    eta: "Today, 16:30",
  },
  {
    id: "approval-2",
    workflowId: "wf-002",
    workflowTitle: "Regional event contracting",
    department: "finance",
    approver: "Martin Keller",
    status: "pending",
    eta: "Today, 18:00",
  },
  {
    id: "approval-3",
    workflowId: "wf-002",
    workflowTitle: "Regional event contracting",
    department: "legal",
    approver: "Paula Almeida",
    status: "changes_requested",
    eta: "Waiting on clause revision",
  },
  {
    id: "approval-4",
    workflowId: "wf-003",
    workflowTitle: "Distributor rebate refresh",
    department: "finance",
    approver: "Martin Keller",
    status: "changes_requested",
    eta: "Reforecast due tomorrow",
  },
];

export const documentAutomationCards: DocumentAutomationCard[] = [
  {
    id: "doc-1",
    title: "Vendor due diligence packet",
    template: "PROC-QUAL-07",
    automationLevel: "ready_for_handoff",
    owner: "Procurement Operations",
    lastUpdated: "2026-03-10",
    note: "Routes attachments, bank details, and compliance questionnaires automatically.",
  },
  {
    id: "doc-2",
    title: "Market event agreement set",
    template: "LEGAL-EVENT-14",
    automationLevel: "semi_automatic",
    owner: "Legal Operations",
    lastUpdated: "2026-03-08",
    note: "Builds bilingual agreements and flags country-specific clauses for review.",
  },
  {
    id: "doc-3",
    title: "Budget release memo",
    template: "FIN-CAPEX-03",
    automationLevel: "guided",
    owner: "Finance Control",
    lastUpdated: "2026-03-07",
    note: "Pre-fills cost centers and approval thresholds for regional controllers.",
  },
  {
    id: "doc-4",
    title: "Executive exception summary",
    template: "EXEC-DECISION-02",
    automationLevel: "ready_for_handoff",
    owner: "Executive Programme Office",
    lastUpdated: "2026-03-09",
    note: "Summarizes prior decisions, risk notes, and market impact before steering review.",
  },
];

export const documentTemplates: DocumentTemplate[] = [
  {
    id: "template-1",
    code: "PROC-QUAL-07",
    name: "Supplier qualification packet",
    department: "procurement",
    automationLevel: "ready_for_handoff",
    languages: ["English", "Italian", "Spanish"],
    coverage: "All vendor onboarding workflows",
  },
  {
    id: "template-2",
    code: "LEGAL-EVENT-14",
    name: "Event contracting pack",
    department: "legal",
    automationLevel: "semi_automatic",
    languages: ["English", "Spanish", "Portuguese"],
    coverage: "Education events and congress operations",
  },
  {
    id: "template-3",
    code: "FIN-CAPEX-03",
    name: "Budget authorization memo",
    department: "finance",
    automationLevel: "guided",
    languages: ["English", "Spanish"],
    coverage: "Capital and operating expense approvals",
  },
  {
    id: "template-4",
    code: "EXEC-DECISION-02",
    name: "Executive exception brief",
    department: "executive_management",
    automationLevel: "ready_for_handoff",
    languages: ["English", "Arabic"],
    coverage: "Threshold exceptions and steering approvals",
  },
];

export const aiInsights: SentimentInsight[] = [
  {
    id: "ai-1",
    countryCode: "IT",
    label: "positive",
    score: 88,
    topic: "Vendor readiness narrative",
    summary: "Supporting notes from procurement show clear ownership and low ambiguity.",
    recommendedAction: "Keep the approval window unchanged and reuse the same packet structure.",
  },
  {
    id: "ai-2",
    countryCode: "BR",
    label: "attention",
    score: 61,
    topic: "Contract clause friction",
    summary: "Legal comments show repeated concern around liability wording in translated annexes.",
    recommendedAction: "Escalate the Portuguese contract annex for clause harmonization before steering review.",
  },
  {
    id: "ai-3",
    countryCode: "MX",
    label: "attention",
    score: 58,
    topic: "Budget confidence drift",
    summary: "Finance commentary shifted from confident to cautious after the latest rebate assumptions.",
    recommendedAction: "Re-run the accrual scenario with commercial before requesting executive approval.",
  },
  {
    id: "ai-4",
    countryCode: "AE",
    label: "neutral",
    score: 74,
    topic: "Arabic documentation flow",
    summary: "Teams are aligned on translation timelines, but document routing still depends on one reviewer.",
    recommendedAction: "Add a secondary legal reviewer for Arabic packets in the executive exception lane.",
  },
];

export const countryPipelineSnapshots: CountryPipelineSnapshot[] = [
  {
    countryCode: "IT",
    countryName: "Italy",
    coordinationNote: "Procurement is pacing the current queue. Finance and legal are within SLA.",
    stages: [
      { department: "commercial", active: 4, approved: 3, atRisk: 0, owner: "Elena Rossi" },
      { department: "procurement", active: 5, approved: 2, atRisk: 1, owner: "Sofia Ortega" },
      { department: "finance", active: 3, approved: 2, atRisk: 0, owner: "Martin Keller" },
      { department: "legal", active: 2, approved: 1, atRisk: 0, owner: "Paula Almeida" },
      { department: "executive_management", active: 1, approved: 0, atRisk: 0, owner: "Nadia Haddad" },
    ],
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    coordinationNote: "Finance exceptions require refreshed commercial assumptions before the next cut-off.",
    stages: [
      { department: "commercial", active: 6, approved: 5, atRisk: 0, owner: "Elena Rossi" },
      { department: "procurement", active: 4, approved: 3, atRisk: 0, owner: "Sofia Ortega" },
      { department: "finance", active: 4, approved: 1, atRisk: 2, owner: "Martin Keller" },
      { department: "legal", active: 3, approved: 1, atRisk: 1, owner: "Paula Almeida" },
      { department: "executive_management", active: 2, approved: 0, atRisk: 0, owner: "Nadia Haddad" },
    ],
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    coordinationNote: "Legal review is the pacing item. Executive release is reserved for the current high-priority package.",
    stages: [
      { department: "commercial", active: 5, approved: 4, atRisk: 0, owner: "Elena Rossi" },
      { department: "procurement", active: 3, approved: 3, atRisk: 0, owner: "Sofia Ortega" },
      { department: "finance", active: 4, approved: 2, atRisk: 0, owner: "Martin Keller" },
      { department: "legal", active: 4, approved: 1, atRisk: 2, owner: "Paula Almeida" },
      { department: "executive_management", active: 1, approved: 0, atRisk: 0, owner: "Nadia Haddad" },
    ],
  },
  {
    countryCode: "AE",
    countryName: "United Arab Emirates",
    coordinationNote: "Translation dependencies are stable. Executive management is reviewing one exception pack.",
    stages: [
      { department: "commercial", active: 2, approved: 2, atRisk: 0, owner: "Elena Rossi" },
      { department: "procurement", active: 2, approved: 1, atRisk: 0, owner: "Sofia Ortega" },
      { department: "finance", active: 2, approved: 1, atRisk: 0, owner: "Martin Keller" },
      { department: "legal", active: 3, approved: 2, atRisk: 0, owner: "Paula Almeida" },
      { department: "executive_management", active: 2, approved: 1, atRisk: 0, owner: "Nadia Haddad" },
    ],
  },
];

export const languageCoverage: LanguageCoverage[] = [
  {
    language: "English",
    countries: ["IT", "ES", "MX", "BR", "AE"],
    translatorMode: "Primary operating language for cross-border review packs",
    complianceSupport: "Master policy language and executive summary baseline",
  },
  {
    language: "Italian",
    countries: ["IT"],
    translatorMode: "Local commercial and vendor packet delivery",
    complianceSupport: "Market-specific event and distributor forms",
  },
  {
    language: "Spanish",
    countries: ["ES", "MX"],
    translatorMode: "Iberia and LATAM operating packs",
    complianceSupport: "Pricing, rebate, and procurement policy variants",
  },
  {
    language: "Portuguese",
    countries: ["BR"],
    translatorMode: "Contracting and event annex coverage",
    complianceSupport: "Brazil event documentation controls",
  },
  {
    language: "Arabic",
    countries: ["AE"],
    translatorMode: "Executive exception and affiliate support",
    complianceSupport: "Document traceability and market submission packs",
  },
];

export const notificationFeed: NotificationItem[] = [
  {
    id: "notif-1",
    channel: "in_app",
    status: "queued",
    title: "Finance review due today",
    message: "Two LATAM workflows need finance confirmation before the regional close window.",
    audience: "Regional Finance Control",
    scheduledFor: "Today, 15:00",
  },
  {
    id: "notif-2",
    channel: "email",
    status: "delivered",
    title: "Executive brief generated",
    message: "The current steering pack was assembled with the latest legal and AI sentiment notes.",
    audience: "Executive Steering Committee",
    scheduledFor: "Today, 09:00",
  },
  {
    id: "notif-3",
    channel: "slack",
    status: "action_required",
    title: "Translation fallback requested",
    message: "Arabic document backup reviewer is required for the next UAE exception workflow.",
    audience: "Legal Operations",
    scheduledFor: "Tomorrow, 08:30",
  },
];
